repo=c("http://cran.ma.imperial.ac.uk/")
lib=Sys.getenv("R_LIBS_USER")

install.packages("httpuv", lib=lib, repos=repo)
install.packages("shiny", lib=lib, repos=repo)
install.packages("RSQLite", lib=lib, repos=repo)
install.packages("ggplot2", lib=lib, repos=repo)
install.packages("jpeg", lib=lib, repos=repo)
install.packages("reshape2", lib=lib, repos=repo)
install.packages("chron", lib=lib, repos=repo)
install.packages("scales", lib=lib, repos=repo)
install.packages("mapproj", lib=lib, repos=repo)
install.packages("gridExtra", lib=lib, repos=repo)
install.packages("leaflet", lib=lib, repos=repo)
