#!/usr/bin/env Rscript
# Initialise
callingScriptPath <- function() {
  argv <- commandArgs(trailingOnly = FALSE)
  normalizePath(sub("--file=", "", argv[grep("--file=", argv)]))
}
source(file.path(dirname(callingScriptPath()), "src", "init.R"))

# Clean directories, if requested
if(!is.null(args$clean)) {
  removeDirs(args)
  quit(status=0)
}

# Get imports and deps
cat("Getting imports and dependencies...\n")
cat("  * Getting recursive dependencies from", args$repos, "\n")
availablePkgsDb <- available.packages(repos=args$repos)
pkgDepsDf <- getImportedPkgsDepsDf(
  path=args$path,
  ignore_regex=args$ignore,
  availablePkgsDb=availablePkgsDb,
  includeSuggests=args$include_suggests
)
depsSummaryDf <- summarisePkgDepsDf(
  pkgDepsDf,
  availablePkgsDb=availablePkgsDb
)

# Show dependency list
invisible(printDepsFromDf(depsSummaryDf))
if(nrow(depsSummaryDf)==0 || args$listdeps) quit(status=0)

# Create local repo (and quit), if requested
if(args$create_local_repo) {
  cat("Creating local CRAN-like repo under", args$output_dirs$sources, "...\n\n")
  createLocalRepo(pkgsDf=depsSummaryDf, destdir=args$output_dirs$sources)
  cat("Done creating local CRAN-like repo.\n")
  cat("  > Path to sources:", args$output_dirs$sources, "\n")
  quit(status=0)
}

# Install packages
installPkgsFromDf(
  df=depsSummaryDf,
  repos=args$repos,
  binDirs=args$bin_repo_path,
  outputDirs=args$output_dirs,
  liveViewLog=args$live_view_install_log,
  keepFullLog=args$keep_full_install_log,
  available=availablePkgsDb,
  configure.args=args$configure_args,
  configure.vars=args$configure_vars
)
cat("Done.\n")
