#!/usr/bin/env Rscript
args <- commandArgs(trailingOnly = FALSE)

# Changing work dir to obsmonSrcDir, so all needed files can be found
thisFilePath <- normalizePath(sub("--file=", "", args[grep("--file=", args)]))
# Accounting for the fact that the script may be executed via a symlink
obsmonSrcDir <- dirname(Sys.readlink(thisFilePath))
if(obsmonSrcDir=="" || is.na(obsmonSrcDir)) obsmonSrcDir<-dirname(thisFilePath)
setwd(obsmonSrcDir)

# Initialising
source("init.R")

# Running the shinny app. This routine is defined in the file init.R
runAppHandlingBusyPort(appDir=obsmonSrcDir, defaultPort=5391)
